import { AdvertiserShell } from "@/components/advertiser/AdvertiserShell";
import { requireAdvertiserContext } from "@/lib/advertiser/auth";
import { approveBonus, calculateBonuses } from "./actions";

export const dynamic = "force-dynamic";
const input = "mt-1 min-h-10 w-full rounded-xl border border-slate-300 bg-white px-3";
const movementSign: Record<string, number> = { issued: 1, adjustment: 1, returned: -1, distributed: -1, lost: -1 };
const etb = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "ETB", maximumFractionDigits: 2 }).format(value);

export default async function OperationsPage({ searchParams }: { searchParams: Promise<{ message?: string; error?: string }> }) {
  const [{ supabase, memberships }, query] = await Promise.all([requireAdvertiserContext(), searchParams]);
  const companyIds = memberships.map((m) => m.company_id);
  const names = Object.fromEntries(memberships.map((m) => [m.company_id, m.companies?.name || "Company"]));
  const { data: campaigns, error: campaignError } = companyIds.length ? await supabase.from("campaigns").select("id,company_id,name,status").in("company_id", companyIds).order("name") : { data: [], error: null };
  if (campaignError) throw new Error(campaignError.message);
  const campaignIds = (campaigns || []).map((c) => c.id);
  const [assignmentsResult, leadsResult, complianceResult, inventoryResult, bonusesResult] = campaignIds.length ? await Promise.all([
    supabase.from("driver_campaign_assignments").select("driver_id,campaign_id,drivers(id,full_name,vehicle_plate,compliance_score)").in("campaign_id", campaignIds).in("status", ["active", "completed"]),
    supabase.from("leads").select("driver_id,campaign_id,verification_status").in("campaign_id", campaignIds).in("verification_status", ["otp_verified", "call_verified"]).is("deleted_at", null),
    supabase.from("driver_compliance_records").select("id,driver_id,campaign_id,record_date,checkin_time,checkin_photo_path,inventory_reported,compliance_flag,flag_reason").in("campaign_id", campaignIds).order("record_date", { ascending: false }).limit(100),
    supabase.from("inventory_movements").select("id,driver_id,campaign_id,movement_type,quantity,occurred_at,notes").in("campaign_id", campaignIds).order("occurred_at", { ascending: false }).limit(200),
    supabase.from("driver_bonuses").select("id,driver_id,campaign_id,base_fee_etb,lead_bonus_etb,top_driver_prize_etb,compliance_deduction_etb,verified_leads_count,compliance_score_at_close,status,approved_at").in("campaign_id", campaignIds).order("verified_leads_count", { ascending: false }),
  ]) : [{ data: [], error: null }, { data: [], error: null }, { data: [], error: null }, { data: [], error: null }, { data: [], error: null }];
  const firstError = [assignmentsResult, leadsResult, complianceResult, inventoryResult, bonusesResult].find((r) => r.error)?.error;
  if (firstError) throw new Error(firstError.message);
  const campaignNames = Object.fromEntries((campaigns || []).map((c) => [c.id, c.name]));
  const driverNames = Object.fromEntries((assignmentsResult.data || []).map((a) => [a.driver_id, a.drivers?.full_name || "Driver"]));
  const verified = new Map<string, number>();
  for (const lead of leadsResult.data || []) if (lead.driver_id) verified.set(`${lead.campaign_id}:${lead.driver_id}`, (verified.get(`${lead.campaign_id}:${lead.driver_id}`) || 0) + 1);
  const ranked = (assignmentsResult.data || []).map((a) => ({ ...a, count: verified.get(`${a.campaign_id}:${a.driver_id}`) || 0 })).sort((a, b) => b.count - a.count || (b.drivers?.compliance_score || 0) - (a.drivers?.compliance_score || 0));
  const stock = new Map<string, number>();
  for (const row of inventoryResult.data || []) stock.set(`${row.campaign_id}:${row.driver_id}`, (stock.get(`${row.campaign_id}:${row.driver_id}`) || 0) + (movementSign[row.movement_type] || 0) * row.quantity);
  const canApprove = memberships.some((m) => m.can_update_lead_status);
  return <AdvertiserShell title="Campaign operations" companies={Object.values(names)}>
    <p className="mt-3 text-slate-600">Review driver stock, daily compliance, performance ranking, and controlled bonus approvals.</p>
    {query.message && <p className="mt-5 rounded-xl bg-emerald-50 p-3 font-semibold text-emerald-900">{query.message}</p>}{query.error && <p className="mt-5 rounded-xl bg-red-50 p-3 font-semibold text-red-900">{query.error}</p>}
    <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-black">Leaderboard</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="py-3">Rank</th><th>Driver</th><th>Campaign</th><th>Verified leads</th><th>Compliance</th></tr></thead><tbody>{ranked.map((r, i) => <tr key={`${r.campaign_id}:${r.driver_id}`} className="border-b last:border-0"><td className="py-3 font-black">#{i + 1}</td><td>{r.drivers?.full_name}<span className="block text-xs text-slate-500">{r.drivers?.vehicle_plate || "No plate"}</span></td><td>{campaignNames[r.campaign_id]}</td><td className="font-black">{r.count}</td><td>{r.drivers?.compliance_score}%</td></tr>)}</tbody></table></div></section>
    <div className="mt-6 grid gap-6 xl:grid-cols-2">
      <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-black">Inventory report</h2><div className="mt-4 space-y-3">{ranked.map((r) => <div key={`${r.campaign_id}:${r.driver_id}`} className="flex justify-between rounded-xl bg-slate-50 p-3"><span><strong>{r.drivers?.full_name}</strong><small className="block text-slate-500">{campaignNames[r.campaign_id]}</small></span><span className="text-right text-lg font-black">{stock.get(`${r.campaign_id}:${r.driver_id}`) || 0}<small className="block text-xs font-normal text-slate-500">units on hand</small></span></div>)}</div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-black">Compliance review</h2><div className="mt-4 space-y-3">{(complianceResult.data || []).map((r) => <article key={r.id} className={`rounded-xl border p-3 ${r.compliance_flag ? "border-red-200 bg-red-50" : "border-emerald-200 bg-emerald-50"}`}><div className="flex justify-between gap-3"><strong>{driverNames[r.driver_id]}</strong><span className="text-sm">{r.record_date}</span></div><p className="mt-1 text-sm">{r.checkin_time ? "Checked in" : "Missing check-in"} · Inventory reported: {r.inventory_reported ?? "—"}</p>{r.flag_reason && <p className="mt-1 text-sm font-semibold text-red-800">{r.flag_reason}</p>}</article>)}{!complianceResult.data?.length && <p className="text-sm text-slate-500">No compliance check-ins recorded.</p>}</div></section>
    </div>
    <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-black">Bonus calculation and approval</h2><form action={calculateBonuses} className="mt-4 grid gap-3 md:grid-cols-3 xl:grid-cols-6"><label className="text-xs font-bold">Campaign<select name="campaignId" required className={input}>{(campaigns || []).map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-xs font-bold">Base fee ETB<input name="baseFee" type="number" min="0" step="0.01" defaultValue="1000" className={input}/></label><label className="text-xs font-bold">Per verified lead<input name="perLead" type="number" min="0" step="0.01" defaultValue="50" className={input}/></label><label className="text-xs font-bold">Top-driver prize<input name="topPrize" type="number" min="0" step="0.01" defaultValue="500" className={input}/></label><label className="text-xs font-bold">Compliance threshold<input name="complianceThreshold" type="number" min="0" max="100" defaultValue="80" className={input}/></label><label className="text-xs font-bold">Deduction ETB<input name="deduction" type="number" min="0" step="0.01" defaultValue="200" className={input}/></label><button disabled={!canApprove || !campaigns?.length} className="min-h-11 rounded-xl bg-slate-950 px-4 font-bold text-white md:col-span-3 xl:col-span-6 disabled:opacity-40">Calculate pending bonuses</button></form>
      <div className="mt-6 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="py-3">Driver</th><th>Campaign</th><th>Leads</th><th>Total</th><th>Status</th><th>Decision</th></tr></thead><tbody>{(bonusesResult.data || []).map((b) => { const total = Number(b.base_fee_etb) + Number(b.lead_bonus_etb) + Number(b.top_driver_prize_etb) - Number(b.compliance_deduction_etb); return <tr key={b.id} className="border-b last:border-0"><td className="py-3 font-bold">{driverNames[b.driver_id]}</td><td>{campaignNames[b.campaign_id]}</td><td>{b.verified_leads_count}</td><td className="font-black">{etb(total)}</td><td>{b.status}</td><td>{b.status === "pending" && canApprove ? <form action={approveBonus} className="flex items-center gap-2"><input type="hidden" name="bonusId" value={b.id}/><input type="hidden" name="campaignId" value={b.campaign_id}/><label className="text-xs"><input type="checkbox" name="confirmation" value="approve" required/> Confirm</label><button className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-black text-white">Approve</button></form> : "—"}</td></tr>})}</tbody></table></div>
    </section>
  </AdvertiserShell>;
}
