import { AdminShell, EmptyState, Notice } from "@/components/admin/AdminShell";
import { createCompany, updateCompanyLogo, updateCompanyProfile, updateCompanyStatus } from "@/app/admin/actions";
import { requirePlatformAdmin } from "@/lib/admin/auth";
import { createAdminClient } from "@/lib/supabase/admin";
export const dynamic="force-dynamic"; const input="mt-2 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 outline-none focus:border-red-800";
export default async function CompaniesPage({searchParams}:{searchParams:Promise<{message?:string;error?:string}>}){const[actor,query]=await Promise.all([requirePlatformAdmin(),searchParams]);const{data:companies,error}=await createAdminClient().from("companies").select("id,identifier,name,sector,status,brand_color,description,services_summary,public_contact_email,public_contact_phone,whatsapp_url,website_url").order("created_at",{ascending:false});if(error)throw new Error(`Unable to load companies: ${error.message}`);return <AdminShell title="Advertiser companies" eyebrow="Tenant setup" adminName={actor.full_name||actor.email}><Notice {...query}/><div className="mt-8 grid gap-7 xl:grid-cols-[.82fr_1.18fr]">
<form action={createCompany} className="h-fit rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Create company</h2><p className="mt-2 text-sm text-slate-500">Start in draft status, then add branding and public information.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Company name"><input className={input} name="name" required maxLength={120}/></Field><Field label="Identifier"><input className={input} name="identifier" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="noah-real-estate"/></Field><Field label="Sector"><input className={input} name="sector" required/></Field><Field label="Brand color"><input className={`${input} h-11 p-1`} name="brandColor" type="color" defaultValue="#8d2114"/></Field><Field label="Public email"><input className={input} name="contactEmail" type="email"/></Field><Field label="Public phone"><input className={input} name="contactPhone"/></Field></div><Field label="Description"><textarea className={`${input} min-h-24 py-3`} name="description" maxLength={500}/></Field><button className="mt-5 min-h-11 w-full rounded-xl bg-slate-950 px-4 font-black text-white">Create draft company</button></form>
<section><h2 className="text-xl font-black">Company directory</h2><div className="mt-4 space-y-4">{!companies?.length?<EmptyState>No companies created yet.</EmptyState>:companies.map(c=><article key={c.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex gap-3"><span className="mt-1 size-4 rounded-full" style={{backgroundColor:c.brand_color||"#cbd5e1"}}/><div><h3 className="font-black">{c.name}</h3><p className="text-sm text-slate-500">{c.identifier} · {c.sector}</p><p className="mt-2 text-xs font-bold uppercase text-red-800">{c.status}</p></div></div><form action={updateCompanyStatus} className="flex gap-2"><input type="hidden" name="id" value={c.id}/><select name="status" defaultValue={c.status} className="rounded-lg border px-3"><option>draft</option><option>active</option><option>inactive</option><option>archived</option></select><button className="rounded-lg bg-slate-100 px-3 font-bold">Update</button></form></div>
<form action={updateCompanyLogo} encType="multipart/form-data" className="mt-5 flex flex-col gap-3 border-t pt-4 sm:flex-row sm:items-end"><input type="hidden" name="id" value={c.id}/><Field label="Company logo (PNG, JPEG, WebP · max 2 MB)"><input className={`${input} py-2`} name="logo" type="file" accept="image/png,image/jpeg,image/webp" required/></Field><button className="min-h-11 rounded-xl bg-slate-950 px-4 font-black text-white">Upload logo</button></form>
<details className="mt-4 border-t pt-4"><summary className="cursor-pointer text-sm font-black text-red-800">Edit public company information</summary><form action={updateCompanyProfile} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="id" value={c.id}/><Field label="About company" wide><textarea name="description" maxLength={500} defaultValue={c.description||""} className={`${input} min-h-24 py-3`}/></Field><Field label="Services / products" wide><textarea name="servicesSummary" maxLength={1000} defaultValue={c.services_summary||""} className={`${input} min-h-24 py-3`}/></Field><Field label="Public email"><input name="contactEmail" type="email" defaultValue={c.public_contact_email||""} className={input}/></Field><Field label="Public phone"><input name="contactPhone" defaultValue={c.public_contact_phone||""} className={input}/></Field><Field label="WhatsApp URL"><input name="whatsappUrl" type="url" defaultValue={c.whatsapp_url||""} className={input}/></Field><Field label="Website URL"><input name="websiteUrl" type="url" defaultValue={c.website_url||""} className={input}/></Field><button className="min-h-11 rounded-xl bg-slate-950 px-4 font-black text-white sm:col-span-2">Save public information</button></form></details></article>)}</div></section></div></AdminShell>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={`block min-w-0 text-sm font-bold ${wide?"sm:col-span-2":""}`}>{label}{children}</label>}
