"use server";
import{revalidatePath}from"next/cache";import{redirect}from"next/navigation";import{z}from"zod";import{requireAdvertiserContext}from"@/lib/advertiser/auth";
import { createAdminClient } from "@/lib/supabase/admin";
const uuid=z.uuid();const val=(f:FormData,k:string)=>String(f.get(k)||"").trim();function done(path:string,kind:"message"|"error",msg:string):never{revalidatePath(path);redirect(`${path}?${kind}=${encodeURIComponent(msg)}`)}
export async function addLeadActivity(fd:FormData){const leadId=uuid.safeParse(val(fd,"leadId"));const type=z.enum(["call","sms","email","whatsapp","telegram","appointment","note"]).safeParse(val(fd,"type"));const status=z.enum(["planned","in_progress","completed","cancelled"]).safeParse(val(fd,"status"));if(!leadId.success||!type.success||!status.success)done("/advertiser/leads","error","Invalid activity.");const{supabase,user,memberships}=await requireAdvertiserContext();const{data:lead}=await supabase.from("leads").select("id,company_id").eq("id",leadId.data).maybeSingle();if(!lead||!memberships.some(m=>m.company_id===lead.company_id&&m.can_update_lead_status))done("/advertiser/leads","error","Activity permission required.");const now=new Date().toISOString();const{error}=await supabase.from("lead_activities").insert({lead_id:lead.id,company_id:lead.company_id,activity_type:type.data,status:status.data,performed_by:user.id,scheduled_at:status.data==="planned"?val(fd,"scheduledAt")||null:null,started_at:status.data==="in_progress"?now:null,completed_at:status.data==="completed"?now:null,outcome_code:val(fd,"outcome")||null,notes:val(fd,"notes")||null});if(error)done(`/advertiser/leads/${lead.id}`,"error",error.message);done(`/advertiser/leads/${lead.id}`,"message","Activity added.")}
export async function saveCompanyProfile(fd:FormData){const companyId=uuid.safeParse(val(fd,"companyId"));if(!companyId.success)done("/advertiser/settings/profile","error","Invalid company.");const{supabase,memberships}=await requireAdvertiserContext();if(!memberships.some(m=>m.company_id===companyId.data&&m.can_edit_profile))done("/advertiser/settings/profile","error","Profile permission required.");const{error}=await supabase.from("companies").update({name:val(fd,"name"),description:val(fd,"description")||null,services_summary:val(fd,"servicesSummary")||null,public_contact_name:val(fd,"contactName")||null,public_contact_title:val(fd,"contactTitle")||null,public_contact_email:val(fd,"email")||null,website_url:val(fd,"website")||null,telegram_url:val(fd,"telegram")||null}).eq("id",companyId.data);if(error)done("/advertiser/settings/profile","error",error.message);done("/advertiser/settings/profile","message","Company profile updated.")}
export async function addCompanyService(fd:FormData){const companyId=uuid.safeParse(val(fd,"companyId"));if(!companyId.success||val(fd,"name").length<2)done("/advertiser/settings/profile","error","Check service fields.");const{supabase,memberships}=await requireAdvertiserContext();if(!memberships.some(m=>m.company_id===companyId.data&&m.can_edit_profile))done("/advertiser/settings/profile","error","Profile permission required.");const{error}=await supabase.from("company_services").insert({company_id:companyId.data,name:val(fd,"name"),description:val(fd,"description")||null});if(error)done("/advertiser/settings/profile","error",error.message);done("/advertiser/settings/profile","message","Service added.")}
export async function updateAdvertiserFeedback(fd:FormData){const id=uuid.safeParse(val(fd,"id"));const status=z.enum(["viewed","actioned","archived"]).safeParse(val(fd,"status"));if(!id.success||!status.success)done("/advertiser/engagement","error","Invalid feedback.");const{supabase,user,memberships}=await requireAdvertiserContext();const ids=memberships.filter(m=>m.can_update_lead_status).map(m=>m.company_id);const now=new Date().toISOString();const patch=status.data==="viewed"?{status:status.data,viewed_at:now,viewed_by:user.id}:status.data==="actioned"?{status:status.data,actioned_at:now,actioned_by:user.id}:{status:status.data,archived_at:now};const{error}=await supabase.from("lead_feedback").update(patch).eq("id",id.data).in("company_id",ids);if(error)done("/advertiser/engagement","error",error.message);done("/advertiser/engagement","message","Feedback updated.")}

export async function addTeamMember(fd: FormData) {
  const parsed = z.object({ companyId: z.uuid(), email: z.email(), fullName: z.string().trim().min(2).max(100), temporaryPassword: z.string().min(12).max(128) }).safeParse(Object.fromEntries(fd));
  if (!parsed.success) done("/advertiser/settings/team", "error", "Check the member name, email, and 12-character temporary password.");
  const { user, memberships } = await requireAdvertiserContext();
  if (!memberships.some((membership) => membership.company_id === parsed.data.companyId && membership.can_manage_team)) done("/advertiser/settings/team", "error", "Team-management permission required.");
  const admin = createAdminClient(); const { count } = await admin.from("company_memberships").select("user_id", { count: "exact", head: true }).eq("company_id", parsed.data.companyId).eq("active", true); const { data: settings } = await admin.from("app_settings").select("max_company_representatives").eq("id", 1).single();
  if ((count || 0) >= (settings?.max_company_representatives || 5)) done("/advertiser/settings/team", "error", "The company representative limit has been reached.");
  const { data: created, error: userError } = await admin.auth.admin.createUser({ email: parsed.data.email.toLowerCase(), password: parsed.data.temporaryPassword, email_confirm: true, user_metadata: { full_name: parsed.data.fullName } });
  if (userError || !created.user) done("/advertiser/settings/team", "error", userError?.message || "Unable to create representative.");
  await admin.from("profiles").update({ full_name: parsed.data.fullName }).eq("id", created.user.id);
  const { error } = await admin.from("company_memberships").insert({ company_id: parsed.data.companyId, user_id: created.user.id, can_view_leads: true, can_update_lead_status: true, can_export_leads: val(fd,"canExport")==="on", can_edit_profile: false, can_manage_notifications: false, can_manage_team: false, created_by: user.id });
  if (error) { await admin.auth.admin.deleteUser(created.user.id); done("/advertiser/settings/team", "error", error.message); }
  done("/advertiser/settings/team", "message", "Representative account created.");
}

export async function updateTeamMember(fd: FormData) {
  const companyId = uuid.safeParse(val(fd,"companyId")); const userId = uuid.safeParse(val(fd,"userId")); if(!companyId.success||!userId.success) done("/advertiser/settings/team","error","Invalid team member.");
  const { user, memberships } = await requireAdvertiserContext(); if(!memberships.some((membership)=>membership.company_id===companyId.data&&membership.can_manage_team)) done("/advertiser/settings/team","error","Team-management permission required.");
  if(user.id===userId.data&&val(fd,"active")!=="on") done("/advertiser/settings/team","error","You cannot deactivate your own account.");
  const {error}=await createAdminClient().from("company_memberships").update({active:val(fd,"active")==="on",can_edit_profile:val(fd,"canEditProfile")==="on",can_view_leads:val(fd,"canViewLeads")==="on",can_export_leads:val(fd,"canExportLeads")==="on",can_update_lead_status:val(fd,"canUpdateLeads")==="on",can_manage_notifications:val(fd,"canManageNotifications")==="on",can_manage_team:val(fd,"canManageTeam")==="on"}).eq("company_id",companyId.data).eq("user_id",userId.data);
  if(error)done("/advertiser/settings/team","error",error.message);done("/advertiser/settings/team","message","Member permissions updated.");
}
