import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowRight, BriefcaseBusiness, CarFront, LockKeyhole, QrCode, Settings2 } from "lucide-react";

const portals = [
  { title: "Advertiser portal", eyebrow: "Client teams", description: "Leads, campaign value, notifications, company profile, and team permissions.", href: "/advertiser/login", action: "Advertiser sign in", icon: BriefcaseBusiness, color: "bg-[#df785f]" },
  { title: "Field operations", eyebrow: "AddisPulse field team", description: "Driver check-ins, compliance evidence, inventory, leaderboard, and bonuses.", href: "/admin/login", action: "Operations sign in", icon: CarFront, color: "bg-[#e8ded0]" },
  { title: "Admin console", eyebrow: "Platform administration", description: "Companies, campaigns, assignments, review, billing, content, QR codes, and controls.", href: "/admin/login", action: "Admin sign in", icon: Settings2, color: "bg-[#f1c7bc]" },
] as const;

export default function PortalPage() {
  return <main className="min-h-screen bg-[#f4f0e8] text-[#17201b]">
    <header className="border-b border-[#17201b]/10"><div className="mx-auto flex max-w-[1280px] items-center justify-between px-5 py-5 sm:px-8"><Link href="/"><Image src="/logo%20(2).png" alt="AddisPulse Media" width={230} height={88} priority className="h-10 w-auto object-contain" /></Link><Link href="/" className="flex items-center gap-2 text-sm font-black"><ArrowLeft className="size-4" /> Back to website</Link></div></header>
    <section className="relative overflow-hidden px-5 py-16 sm:px-8 sm:py-24"><div aria-hidden="true" className="absolute right-[-120px] top-[-160px] size-[440px] rounded-full bg-[#e8ded0]" /><div className="relative mx-auto max-w-[1280px]"><p className="text-xs font-black uppercase tracking-[.2em] text-[#8d2114]">Secure workspace directory</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-.065em] sm:text-7xl">Choose where you work.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#5f6861]">Protected areas require an authorized account. You will only see the company data and tools assigned to your role.</p>
      <div className="mt-12 grid gap-5 lg:grid-cols-3">{portals.map((portal) => { const Icon=portal.icon; return <Link key={portal.title} href={portal.href} className="group flex min-h-[360px] flex-col rounded-[30px] border border-[#17201b]/10 bg-white p-7 transition hover:-translate-y-1 hover:shadow-[0_24px_60px_rgba(23,32,27,.12)]"><div className={`grid size-14 place-items-center rounded-2xl ${portal.color}`}><Icon className="size-6" /></div><p className="mt-10 text-xs font-black uppercase tracking-[.17em] text-[#6b5f5c]">{portal.eyebrow}</p><h2 className="mt-3 text-3xl font-black tracking-[-.04em]">{portal.title}</h2><p className="mt-4 leading-7 text-[#5f6861]">{portal.description}</p><span className="mt-auto flex items-center gap-2 pt-8 font-black">{portal.action}<ArrowRight className="size-5 transition-transform group-hover:translate-x-1" /></span></Link>})}</div>
      <div className="mt-6 grid gap-5 rounded-[30px] bg-[#17201b] p-7 text-white sm:p-9 lg:grid-cols-[auto_1fr_auto] lg:items-center"><span className="grid size-14 place-items-center rounded-2xl bg-white text-[#17201b]"><QrCode className="size-7" /></span><div><p className="text-xs font-black uppercase tracking-[.17em] text-[#f2b1a3]">Passenger experience</p><h2 className="mt-2 text-2xl font-black">Passengers enter through the QR inside their vehicle.</h2><p className="mt-2 text-sm leading-6 text-white/60">No account or app download is needed. The QR opens the active client video, offer, lead form, and OTP submission flow.</p></div><div className="flex items-center gap-2 text-sm font-bold text-white/55"><LockKeyhole className="size-4" /> QR-only access</div></div>
    </div></section>
  </main>;
}
