"use client";
import Image from "next/image";
import { useState } from "react";
import { ExternalLink, Film, LoaderCircle, Play } from "lucide-react";
import { campaignVideoEmbedUrl, shouldShowCampaignMedia } from "@/lib/passenger-flow/ui";
import { passengerDictionary, type PassengerLocale } from "@/lib/passenger-flow/i18n";

export function CampaignMedia({videoUrl,posterUrl,caption,provider,external,locale,logoUrl,companyName}:{videoUrl?:string|null;posterUrl?:string|null;caption?:string|null;provider?:string|null;external?:boolean;locale:PassengerLocale;logoUrl?:string|null;companyName:string}){
 const t=passengerDictionary(locale),[loading,setLoading]=useState(Boolean(videoUrl&&!external)),[failed,setFailed]=useState(false),hasVideo=shouldShowCampaignMedia(videoUrl),embedUrl=videoUrl?campaignVideoEmbedUrl(provider,videoUrl):null;
 if(hasVideo&&embedUrl)return <section className="overflow-hidden rounded-[26px] border border-[#193752] bg-[#0b1f33] shadow-[0_18px_45px_rgba(11,31,51,.18)] lg:mx-auto lg:max-w-3xl"><div className="flex items-center gap-3 bg-[#0b1f33] px-5 py-4 text-white"><span className="grid size-9 place-items-center rounded-full bg-white/10"><Play className="size-4 fill-current"/></span><div><p className="text-xs font-bold uppercase tracking-[.14em] text-white/55">{t.campaignStory}</p><p className="font-bold">{caption||t.watch}</p></div></div><div className="h-52 bg-black sm:aspect-video sm:h-auto"><iframe src={embedUrl} title={caption||t.watch} className="size-full" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen loading="lazy" referrerPolicy="strict-origin-when-cross-origin"/></div></section>;
 if(hasVideo&&videoUrl&&external&&provider!=="cloudinary")return <a href={videoUrl} target="_blank" rel="noreferrer" className="group relative flex h-52 items-end overflow-hidden rounded-[24px] bg-[var(--passenger-navy)] p-5 text-white sm:aspect-video sm:h-auto">{posterUrl&&<span className="absolute inset-0 bg-cover bg-center opacity-55" style={{backgroundImage:`url(${posterUrl})`}}/>}<span className="relative flex items-center gap-3 rounded-2xl bg-black/55 px-4 py-3 text-sm font-bold"><ExternalLink className="size-5"/>{caption||t.watch}</span></a>;
 if(hasVideo&&videoUrl&&!failed)return <div className="relative h-52 overflow-hidden rounded-[24px] bg-[var(--passenger-navy)] sm:aspect-video sm:h-auto lg:mx-auto lg:max-w-3xl">{loading&&<div className="absolute inset-0 grid place-items-center text-white"><LoaderCircle className="size-8 animate-spin"/></div>}<video controls playsInline muted preload="metadata" poster={posterUrl||undefined} onLoadedData={()=>setLoading(false)} onError={()=>{setLoading(false);setFailed(true)}} className="size-full object-cover"><source src={videoUrl}/></video></div>;
 return <div className="flex aspect-video items-center justify-center border-y border-[var(--passenger-line)] bg-[linear-gradient(135deg,var(--passenger-primary-soft),#fff_48%,#eef2f5)] p-6 text-center"><div>{logoUrl?<Image src={logoUrl} alt="" width={80} height={80} unoptimized className="mx-auto h-20 w-20 rounded-2xl object-contain"/>:<Film className="mx-auto size-9 text-[var(--passenger-primary)]"/>}<p className="mt-3 font-bold">{companyName}</p><p className="mt-1 text-sm text-[var(--passenger-muted)]">{caption||t.detailsAvailable}</p></div></div>;
}
