import { AdminShell, Notice } from "@/components/admin/AdminShell";
import { requirePlatformAdmin } from "@/lib/admin/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { handleDeletionRequest, updatePlatformSettings } from "../control-actions";
export const dynamic = "force-dynamic"; const input = "mt-1 min-h-10 w-full rounded-xl border border-slate-300 px-3";
export default async function SystemPage({ searchParams }: { searchParams: Promise<{ message?: string; error?: string }> }) {
  const [actor, query] = await Promise.all([requirePlatformAdmin(), searchParams]); const db = createAdminClient();
  const [{ data: settings }, { data: audits }, { data: logins }, { data: sessions }, { data: deletions }] = await Promise.all([db.from("app_settings").select("*").eq("id", 1).single(), db.from("audit_logs").select("id,actor_role,action,entity_type,entity_id,details,created_at,profiles(full_name),companies(name)").order("created_at", { ascending: false }).limit(100), db.from("login_security_events").select("id,success,failure_reason,created_at").order("created_at", { ascending: false }).limit(100), db.from("user_session_controls").select("session_id,user_id,started_at,last_activity_at,revoked_at,profiles(full_name,email)").order("last_activity_at", { ascending: false }).limit(100), db.from("data_deletion_requests").select("id,requester_name,requester_contact,status,notes,created_at,companies(name)").order("created_at", { ascending: false })]);
  if (!settings) throw new Error("Platform settings row is missing.");
  return <AdminShell title="Platform governance" eyebrow="Settings, audit, security and privacy" adminName={actor.full_name}><Notice {...query}/><form action={updatePlatformSettings} className="mt-7 rounded-2xl bg-white p-5"><h2 className="text-xl font-black">Platform settings</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><label className="text-sm font-bold">Public base URL<input name="baseUrl" defaultValue={settings.public_base_url} className={input}/></label><label className="text-sm font-bold">Lead retention (months)<input name="retention" type="number" min="1" max="120" defaultValue={settings.lead_retention_months} className={input}/></label><label className="text-sm font-bold">Unavailable message<input name="unavailable" defaultValue={settings.default_unavailable_message} className={input}/></label></div><button className="mt-4 rounded-xl bg-slate-950 px-5 py-3 font-bold text-white">Save settings</button></form><section className="mt-6 rounded-2xl bg-white p-5"><h2 className="text-xl font-black">Privacy and deletion requests</h2><div className="mt-4 space-y-3">{(deletions || []).map((item) => <article key={item.id} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-3"><div><strong>{item.requester_name || "Requester"} · {item.companies?.name}</strong><p className="text-sm text-slate-500">{item.requester_contact} · {item.status}</p></div><form action={handleDeletionRequest} className="flex flex-wrap gap-2"><input type="hidden" name="id" value={item.id}/><select name="status" className="rounded-lg border px-2 text-xs"><option>verified</option><option>approved</option><option>completed</option><option>rejected</option></select><input name="notes" placeholder="Decision note" className="rounded-lg border px-2 text-xs"/><button className="rounded-lg bg-slate-950 px-3 text-xs font-bold text-white">Update</button></form></div></article>)}</div></section><div className="mt-6 grid gap-6 xl:grid-cols-3"><Data title="Audit log" rows={(audits || []).map((item) => `${new Date(item.created_at).toLocaleString()} · ${item.profiles?.full_name || item.actor_role || "system"} · ${item.action} ${item.entity_type}`)}/><Data title="Login security" rows={(logins || []).map((item) => `${new Date(item.created_at).toLocaleString()} · ${item.success ? "success" : "failed"} ${item.failure_reason || ""}`)}/><Data title="Sessions" rows={(sessions || []).map((item) => `${item.profiles?.full_name || "User"} · ${item.revoked_at ? "revoked" : "active"} · ${new Date(item.last_activity_at).toLocaleString()}`)}/></div></AdminShell>;
}
function Data({ title, rows }: { title: string; rows: string[] }) { return <section className="rounded-2xl bg-white p-5"><h2 className="text-lg font-black">{title}</h2><div className="mt-3 max-h-96 space-y-2 overflow-auto">{rows.map((row,index) => <p key={index} className="rounded-lg bg-slate-50 p-3 text-xs">{row}</p>)}</div></section>; }
