export const passengerLocales = ["en", "am", "om", "ar"] as const;
export type PassengerLocale = (typeof passengerLocales)[number];

export function passengerLocale(value?: string | null): PassengerLocale {
  return passengerLocales.includes(value as PassengerLocale) ? value as PassengerLocale : "en";
}

const en = {
  languageName: "English", presented: "Presented with RidePerk", welcomeEyebrow: "Welcome aboard",
  welcomeTitle: "Hello, passenger. This offer is for your journey.", welcomeBody: (company: string) => `Discover a verified offer from ${company}. Explore at your own pace, and only share your details if you would like the team to contact you.`,
  request: "Request information", interested: "Interested in this offer?", formIntro: (company: string) => `Share your details, then verify your phone. ${company} may contact you about this campaign.`,
  fullName: "Full name", fullNamePlaceholder: "Enter your full name", phone: "Phone number", phoneHelp: "Ethiopian mobile format, for example 0911 234 567.", email: "Email", optional: "optional", interest: "What interests you?", interestPlaceholder: "Tell us briefly", service: "Interested service", chooseService: "Choose a service",
  consent: (company: string) => `I agree that ${company} may contact me about this campaign.`, secure: "Your information is sent securely.", sending: "Sending verification code…",
  submitDisclaimer: "Submitting does not guarantee a reward unless the campaign terms explicitly confirm eligibility. Your phone is verified to protect the campaign and its passengers.", assigned: (driver: string) => `QR assigned to driver ${driver}.`, secureExperience: "Secure passenger experience",
  contact: (company: string) => `Contact ${company}`, call: "Call", emailAction: "Email", whatsapp: "WhatsApp", details: "What you can explore", campaignStory: "Campaign story", watch: "Watch the offer", discover: "Discover this campaign", detailsAvailable: "Campaign details are available below.",
  errors: { name: "Enter your full name.", phone: "Use an Ethiopian mobile number beginning with 09 or 07.", email: "Enter a valid email address or leave this field blank.", consent: "Confirm your consent before continuing.", connection: "We could not submit your request. Check your connection and try again.", otpDelivery: "Your request was saved, but the verification code could not be sent. Please try again shortly.", generic: "We could not submit your request. Check your details and try again." },
};

export type PassengerDictionary = typeof en;
const dictionaries: Record<PassengerLocale, PassengerDictionary> = {
  en,
  am: { ...en, languageName:"አማርኛ", presented:"በRidePerk የቀረበ", welcomeEyebrow:"እንኳን ደህና መጡ", welcomeTitle:"ሰላም ተሳፋሪ፣ ይህ ቅናሽ ለጉዞዎ ተዘጋጅቷል።", welcomeBody:(c)=>`ከ${c} የቀረበውን የተረጋገጠ ቅናሽ ይመልከቱ። መረጃዎን የሚያጋሩት እንዲያነጋግሩዎት ከፈለጉ ብቻ ነው።`, request:"መረጃ ይጠይቁ", interested:"በዚህ ቅናሽ ፍላጎት አለዎት?", formIntro:(c)=>`መረጃዎን ያጋሩና ስልክዎን ያረጋግጡ። ${c} ስለዚህ ዘመቻ ሊያነጋግርዎት ይችላል።`, fullName:"ሙሉ ስም", fullNamePlaceholder:"ሙሉ ስምዎን ያስገቡ", phone:"ስልክ ቁጥር", phoneHelp:"የኢትዮጵያ ሞባይል ቅርጸት፣ ለምሳሌ 0911 234 567።", email:"ኢሜይል", optional:"አማራጭ", interest:"ምን ፍላጎት አለዎት?", interestPlaceholder:"በአጭሩ ይንገሩን", service:"የሚፈልጉት አገልግሎት", chooseService:"አገልግሎት ይምረጡ", consent:(c)=>`${c} ስለዚህ ዘመቻ እንዲያነጋግረኝ ተስማምቻለሁ።`, secure:"መረጃዎ በደህንነት ይላካል።", sending:"የማረጋገጫ ኮድ በመላክ ላይ…", submitDisclaimer:"ማስገባት ሽልማትን አያረጋግጥም። ስልክዎ ለዘመቻውና ለተሳፋሪዎች ጥበቃ ይረጋገጣል።", assigned:(d)=>`QR ለአሽከርካሪ ${d} ተመድቧል።`, secureExperience:"ደህንነቱ የተጠበቀ የተሳፋሪ ተሞክሮ", contact:(c)=>`${c}ን ያነጋግሩ`, call:"ይደውሉ", emailAction:"ኢሜይል", whatsapp:"ዋትስአፕ", details:"ማየት የሚችሉት", campaignStory:"የዘመቻ ቪዲዮ", watch:"ቅናሹን ይመልከቱ", discover:"ይህን ዘመቻ ይወቁ", detailsAvailable:"የዘመቻው ዝርዝር ከታች ይገኛል።", errors:{name:"ሙሉ ስምዎን ያስገቡ።",phone:"በ09 ወይም 07 የሚጀምር የኢትዮጵያ ሞባይል ቁጥር ይጠቀሙ።",email:"ትክክለኛ ኢሜይል ያስገቡ ወይም ባዶ ይተዉት።",consent:"ከመቀጠልዎ በፊት ፈቃድዎን ያረጋግጡ።",connection:"ጥያቄዎን መላክ አልቻልንም። ግንኙነትዎን ይፈትሹ።",otpDelivery:"ጥያቄዎ ተቀምጧል፣ ግን ኮዱ አልተላከም። እንደገና ይሞክሩ።",generic:"ጥያቄዎን መላክ አልቻልንም። መረጃዎን ይፈትሹ።"}},
  om: { ...en, languageName:"Afaan Oromoo", presented:"RidePerk waliin dhiyaate", welcomeEyebrow:"Baga nagaan dhuftan", welcomeTitle:"Akkam imaltuu, dhiyeessiin kun imala keessaniif qophaa'eera.", welcomeBody:(c)=>`Dhiyeessii mirkanaa'e kan ${c} irraa dhufe ilaalaa. Odeeffannoo keessan kan qooddan yoo akka isin qunnaman barbaaddan qofa.`, request:"Odeeffannoo gaafadhu", interested:"Dhiyeessii kana ni barbaadduu?", formIntro:(c)=>`Odeeffannoo keessan galchaa, bilbila keessan mirkaneessaa. ${c} waa'ee duula kanaa isin qunnamuu danda'a.`, fullName:"Maqaa guutuu", fullNamePlaceholder:"Maqaa guutuu galchi", phone:"Lakkoofsa bilbilaa", phoneHelp:"Bifa bilbila Itoophiyaa, fakkeenyaaf 0911 234 567.", email:"Imeelii", optional:"dirqama miti", interest:"Maal irratti fedhii qabdu?", interestPlaceholder:"Gabaabumatti nutti himi", service:"Tajaajila barbaaddu", chooseService:"Tajaajila filadhu", consent:(c)=>`${c} waa'ee duula kanaa akka na qunnamu nan eeyyama.`, secure:"Odeeffannoon keessan nageenyaan ergama.", sending:"Koodii mirkaneessaa ergaa jira…", submitDisclaimer:"Galchuun badhaasa hin mirkaneessu. Bilbilli keessan duulaa fi imaltoota eeguuf mirkanaa'a.", assigned:(d)=>`QR konkolaachisaa ${d}f ramadame.`, secureExperience:"Muuxannoo imaltuu nageenya qabu", contact:(c)=>`${c} qunnami`, call:"Bilbili", emailAction:"Imeelii", whatsapp:"WhatsApp", details:"Waan ilaaluu dandeessan", campaignStory:"Seenaa duulaa", watch:"Dhiyeessii ilaali", discover:"Duula kana baru", detailsAvailable:"Bal'inni duulaa armaan gaditti jira.", errors:{...en.errors,name:"Maqaa guutuu galchi.",phone:"Lakkoofsa moobaayilaa Itoophiyaa 09 ykn 07n jalqabu fayyadami.",email:"Imeelii sirrii galchi ykn duwwaa dhiisi.",consent:"Itti fufuun dura eeyyama kee mirkaneessi.",connection:"Gaaffii kee erguu hin dandeenye. Walqunnamtii kee ilaali.",otpDelivery:"Gaaffiin kee kuufameera, garuu koodiin hin ergamne. Irra deebi'i.",generic:"Gaaffii kee erguu hin dandeenye. Odeeffannoo kee ilaali."}},
  ar: { ...en, languageName:"العربية", presented:"مقدّم بالتعاون مع RidePerk", welcomeEyebrow:"مرحباً بك", welcomeTitle:"مرحباً أيها الراكب، هذا العرض مخصص لرحلتك.", welcomeBody:(c)=>`اكتشف عرضاً موثوقاً من ${c}. شارك بياناتك فقط إذا كنت ترغب في أن يتواصل معك الفريق.`, request:"اطلب المعلومات", interested:"هل أنت مهتم بهذا العرض؟", formIntro:(c)=>`شارك بياناتك ثم أكّد رقم هاتفك. قد تتواصل معك ${c} بشأن هذه الحملة.`, fullName:"الاسم الكامل", fullNamePlaceholder:"أدخل اسمك الكامل", phone:"رقم الهاتف", phoneHelp:"صيغة هاتف إثيوبي، مثال 0911 234 567.", email:"البريد الإلكتروني", optional:"اختياري", interest:"ما الذي يهمك؟", interestPlaceholder:"أخبرنا باختصار", service:"الخدمة المطلوبة", chooseService:"اختر خدمة", consent:(c)=>`أوافق على أن تتواصل معي ${c} بشأن هذه الحملة.`, secure:"تُرسل معلوماتك بأمان.", sending:"جارٍ إرسال رمز التحقق…", submitDisclaimer:"إرسال الطلب لا يضمن المكافأة. يتم التحقق من هاتفك لحماية الحملة والركاب.", assigned:(d)=>`رمز QR مخصص للسائق ${d}.`, secureExperience:"تجربة آمنة للركاب", contact:(c)=>`تواصل مع ${c}`, call:"اتصال", emailAction:"بريد", whatsapp:"واتساب", details:"ما يمكنك استكشافه", campaignStory:"قصة الحملة", watch:"شاهد العرض", discover:"اكتشف هذه الحملة", detailsAvailable:"تفاصيل الحملة متاحة أدناه.", errors:{...en.errors,name:"أدخل اسمك الكامل.",phone:"استخدم رقم هاتف إثيوبي يبدأ بـ 09 أو 07.",email:"أدخل بريداً صحيحاً أو اتركه فارغاً.",consent:"أكد موافقتك قبل المتابعة.",connection:"تعذر إرسال طلبك. تحقق من الاتصال وحاول مجدداً.",otpDelivery:"تم حفظ طلبك، لكن تعذر إرسال رمز التحقق. حاول لاحقاً.",generic:"تعذر إرسال طلبك. تحقق من البيانات وحاول مجدداً."}},
};

export function passengerDictionary(locale: PassengerLocale) { return dictionaries[locale]; }
