import { AdvertiserShell } from "@/components/advertiser/AdvertiserShell";
import { requireAdvertiserContext } from "@/lib/advertiser/auth";
import { addTeamMember, updateTeamMember } from "../../extended-actions";
export const dynamic = "force-dynamic"; const input = "mt-1 min-h-10 w-full rounded-xl border border-slate-300 px-3";
export default async function TeamPage({ searchParams }: { searchParams: Promise<{ message?: string; error?: string }> }) {
  const [{ supabase, memberships }, query] = await Promise.all([requireAdvertiserContext(), searchParams]); const companyIds = memberships.map((membership) => membership.company_id);
  const { data: team } = companyIds.length ? await supabase.from("company_memberships").select("company_id,user_id,active,can_edit_profile,can_view_leads,can_export_leads,can_update_lead_status,can_manage_notifications,can_manage_team,realtime_enabled,profiles!company_memberships_user_id_fkey(full_name,email),companies(name)").in("company_id", companyIds) : { data: [] };
  const manageable = memberships.filter((membership) => membership.can_manage_team); const names = Object.fromEntries(memberships.map((membership) => [membership.company_id, membership.companies?.name || "Company"]));
  return <AdvertiserShell title="Team & permissions" companies={Object.values(names)}>
    {(query.message || query.error) && <p className={`mt-5 rounded-xl p-3 font-bold ${query.error ? "bg-red-50 text-red-900" : "bg-emerald-50 text-emerald-900"}`}>{query.error || query.message}</p>}
    <div className="mt-7 grid gap-6 xl:grid-cols-[.65fr_1.35fr]">
      <form action={addTeamMember} className="rounded-2xl bg-white p-5"><h2 className="text-xl font-black">Add representative</h2><label className="mt-3 block text-sm font-bold">Company<select name="companyId" className={input}>{manageable.map((membership) => <option key={membership.company_id} value={membership.company_id}>{names[membership.company_id]}</option>)}</select></label><label className="mt-3 block text-sm font-bold">Full name<input name="fullName" required className={input}/></label><label className="mt-3 block text-sm font-bold">Email<input name="email" type="email" required className={input}/></label><label className="mt-3 block text-sm font-bold">Temporary password<input name="temporaryPassword" type="password" minLength={12} required className={input}/></label><label className="mt-3 flex gap-2 text-sm font-bold"><input name="canExport" type="checkbox"/> Allow CSV export</label><button disabled={!manageable.length} className="mt-4 rounded-xl bg-slate-950 px-5 py-3 font-bold text-white disabled:opacity-40">Create representative</button></form>
      <section className="rounded-2xl bg-white p-5"><h2 className="text-xl font-black">Permission register</h2><div className="mt-4 space-y-3">{(team || []).map((member) => <form action={updateTeamMember} key={`${member.company_id}:${member.user_id}`} className="rounded-xl border p-4"><input type="hidden" name="companyId" value={member.company_id}/><input type="hidden" name="userId" value={member.user_id}/><strong>{member.profiles?.full_name}</strong><small className="ml-2 text-slate-500">{member.profiles?.email}</small><p className="text-xs text-slate-500">{member.companies?.name}</p><div className="mt-3 flex flex-wrap gap-3 text-xs">{[["active","Active",member.active],["canEditProfile","Profile",member.can_edit_profile],["canViewLeads","Leads",member.can_view_leads],["canExportLeads","Export",member.can_export_leads],["canUpdateLeads","Pipeline",member.can_update_lead_status],["canManageNotifications","Notifications",member.can_manage_notifications],["canManageTeam","Team",member.can_manage_team]].map(([name,label,checked]) => <label key={String(name)} className="flex gap-1"><input name={String(name)} type="checkbox" defaultChecked={Boolean(checked)}/>{String(label)}</label>)}</div><button disabled={!manageable.some((membership) => membership.company_id === member.company_id)} className="mt-3 rounded-lg border border-slate-300 px-3 py-2 text-xs font-bold disabled:opacity-40">Save permissions</button></form>)}</div></section>
    </div>
  </AdvertiserShell>;
}
